[package]
name = "UQ64x64"
version = "0.3.9"
upgrade_policy = "immutable"

[addresses]
uq64x64 = "0x4e9fce03284c0ce0b86c88dd5a46f050cad2f4f33c4cdd29d98f501868558c81"

[dev-dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/move-stdlib"
addr_subst = { std = "0x1" }
